# This is a basic workflow to help you get started with Actions

name: Docs deploy CI

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    - name: Setup SSH Keys and known_hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        eval "$(ssh-agent -s)"
        ssh-add - <<< "${{ secrets.GH_ACTION_SSH_KEY_PRIVATE }}"
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      
    - name: Node application
      uses: actions/setup-node@v1.1.0

    # installs the deps
    - name: Installation
      run: npm install

    # builds the static website
    - name: build
      run: npm run build
    
    - name: deploy
      run: npm run deploy
      
      
